/*!40000 ALTER TABLE plyometrics DISABLE KEYS */;
INSERT INTO plyometrics (id, name, recommended)
VALUES
  (19, '2 to 1 Box Jump', '3 x 14 Jumps'),
  (20, 'Alternating Bound', '3 x 10 Bounds'),
  (21, 'Bosu Jump', '3 x 14 Jumps'),
  (22, 'Bosu On and Off', '3 x 20 Seconds'),
  (23, 'Bosu Taps', '3 x 20 Seconds'),
  (24, 'Scissors', '3 x 5 Jumps Per Leg'),
  (25, 'Single Leg Box Jumps', '3 x 5 Jumps Per Leg'),
  (26, 'Single Leg Jump with Rotation', '3 x 5 Jumps Per Leg'),
  (27, 'Single Leg Lateral Box Jump', '3 x 8 Jumps Per Leg'),
  (28, 'Staggered Box Jump', '3 x 10 Jumps'),
  (29, 'Staggered Jump', '3 x 10 Jumps');
/*!40000 ALTER TABLE plyometrics ENABLE KEYS */;


/*!40000 ALTER TABLE warmups DISABLE KEYS */;
INSERT INTO warmups (id, name, is_stretch, ex_type)
VALUES
  (19, 'Bosu Body Weight Squat','0', 2),
  (20, 'Bosu One Leg Toe Touch','0', 2),
  (21, 'Bosu Single Leg Taps','0', 2),
  (22, 'Dynamic Calf Stretch','1', 1),
  (23, 'Gate Swings','0', 2),
  (24, 'Leg Stretch Complex','1', 2),
  (25, 'Lunge to Hamstring','0', 2),
  (26, 'Seal Jacks','0', 2),
  (27, 'Toy Soldiers','0', 2),
  (28, 'Transverse Lunge','0', 2);
/*!40000 ALTER TABLE warmups ENABLE KEYS */;


/*!40000 ALTER TABLE tips DISABLE KEYS */;
INSERT INTO tips (exercise_type, tip, exercise_id)
VALUES
  (3,'Use a shorter box than you would normally use for box jumps.',19),
  (3,'Jump off of 2 feet, and land on one foot, alternating the foot you land on.',19),
  (3,'Focus on distance over height.',20),
  (3,'Swing your arms to help maintain your momentum.',20),
  (3,'Focus on height, and swing your arms to help achieve a greater height.',21),
  (3,'Focus on pushing through the leg that is on the bosu.',21),
  (3,'Focus on speed, and swinging your arms.',22),
  (3,'Your knee should not come forward over your toe, keep your weight back.',22),
  (3,'Focus on speed, swinging your arms, and lightly tapping the bosu.',23),
  (3,'Your knee should not come forward over your toe, keep your weight back.',23),
  (3,'Perform the recommended jumps on one leg, and then switch legs.',24),
  (3,'Focus on height and landing in a balanced position, ready to spring up again.',24),
  (3,'Focus on a soft landing, keeping your weight back.',25),
  (3,'Focus on a soft landing, keeping your weight back.',26),
  (3,'Do not let your knee come forward over your toe.',26),
  (3,'On landing, focus on using your glute and hamstring to catch yourself.',26),
  (3,'Use a shorter box than you would normally use for box jumps.',27),
  (3,'Try to strike an even balance between height and distance.',27),
  (3,'Focus on height and keeping your chest up.',28),
  (3,'Focus on height and landing in a lunge position.',29),
  (3,'Do not let your knee come forward over your toe.',29),
  (1,'Perform these at a moderate pace, no need to rush.',19),
  (1,'Keep your weight back.',19),
  (1,'Try to keep the bosu as stable as possible.',19),
  (1,'Keep your knee slightly bent.',20),
  (1,'Perform these at a moderate pace, no need to rush.',20),
  (1,'Spend half the recommended time on one leg, then switch.',20),
  (1,'Spend half the recommended time on one leg, then switch.',21),
  (1,'Spend half the recommended time on one leg, then switch.',22),
  (1,'Perform these at a moderate pace, no need to rush.',23),
  (1,'Use your elbows to push your knees out at the bottom of the squat.',23),
  (1,'Perform these at a moderate pace, no need to rush.',24),
  (1,'Perform these at a moderate pace, no need to rush.',25),
  (1,'Your arms should slightly bent at the elbow, and parallel to the ground.',26),
  (1,'Keep your legs straight to stretch your hamstrings and hips.',27),
  (1,'Keep your chest up, and do not allow your knee to come forward over your toes.',28);
/*!40000 ALTER TABLE tips ENABLE KEYS */;

/*!40000 ALTER TABLE exercises DISABLE KEYS */;
INSERT INTO exercises (id, exercise_type_id, look_up_value, percent_of_luv, category, difficulty,
                       is_body_weight, name, is_image, for_time)
VALUES (189,16,null,null,3,null,'0','2 to 1 V Up','0','0'),
  (190,15,null,null,4,null,'0','6 Inches','0','1'),
  (191, 11, 3, 1, 7, null,'0','Angled Cable Row','0','0'),
  (192, 11, null, null, 4, null,'0','Battleropes Big Circles','0','1'),
  (193, 11, null, null, 4, null,'0','Battleropes Drummers','0','1'),
  (194, 11, null, null, 4, null,'0','Battleropes Front Raises','0','1'),
  (137, 11, null, null, 4, null,'0','Battleropes Lateral Raises','0','1'),
  (138, 11, null, null, 4, null,'0','Battleropes Outward Circles','0','1'),
  (139, 11, null, null, 4, null,'0','Battleropes Side to Side','0','1'),
  (140, 11, null, null, 4, null,'0','Battleropes Single Arm Circles','0','1'),
  (141, 1, null, null, 4, null,'0','Battleropes Slams','0','1'),
  (142, 1, 2, .4, 2, null,'0','Bosu Kettlebell Swing Through','0','0'),
  (143, 9, null, null, 6, null,'0','Bosu Low to High Chop with Med Ball','0','0'),
  (144, 6, null, null, 3, null,'0','Bosu Over and Back Pushup','0','0'),
  (145, 15, null, null, 4, null,'0','Bosu Plank 1','0','1'),
  (146, 15, null, null, 4, null,'0','Bosu Plank 2','0','1'),
  (147, 6, null, null, 3, null,'0','Bosu Pushup','0','0'),
  (148, 8, 2, .24, 2, null,'0','Bosu Single Leg Shoulder Press','0','0'),
  (149, 2, null, null, 4, null,'0','Bosu Single Leg Squat','0','1'),
  (150, 2, 2, .17, 9, null,'0','Bosu Single Leg Squat','0','0'),
  (151, 14, 3, .6, 7, null,'0','Cable Core Anti Rotation','0','1'),
  (152, 14, null, null, 3, null,'0','Cliffhangers','0','0'),
  (153, 2, 1, .52, 1, null,'0','Dumbbell Bulgarian Split Squat','0','0'),
  (154, 2, 1, .52, 1, null,'0','Dumbbell Drop Lunge','0','0'),
  (155, 16, null, null, 3, null,'0','Elbow to Knee','0','0'),
  (156, 10, null, null, 3, null,'0','Elevated Horizontal Side to Side Pullup','0','0'),
  (157, 15, null, null, 4, null,'0','Front Plank Complex','0','1'),
  (158, 1, 2, .23, 2, null,'0','Hang Kettlebell Snatch','0','0'),
  (159, 1, 2, .23, 2, null,'0','Kettlebell Snatch','0','0'),
  (160, 1, 2, .45, 2, null,'0','Kettlebell Swing Through','0','0'),
  (161, 7, null, null, 6, null,'0','Kneeling Med Ball Wall Blasts','0','0'),
  (162, 1, null, null, 8, null,'0','Landmine with Extension','0','0'),
  (163, 16, null, null, 8, null,'0','Little Bigs','0','0'),
  (164, 14, null, null, 6, null,'0','Med Ball Front Rotation','0','0'),
  (165, 16, null, null, 6, null,'0','Med Ball Reverse Crunch with Bridge','0','0'),
  (166, 7, null, null, 6, null,'0','Med Ball Wall Blasts','0','0'),
  (167, 15, null, null, 4, null,'0','One Arm Bosu Plank','0','1'),
  (168, 2, 1, .52, 1, null,'0','Paperboy','0','0'),
  (169, 15, null, null, 4, null,'0','Swiss Ball Plank Complex','0','1'),
  (170, 6, null, null, 3, null,'0','Plyo Pushup with Med Ball','0','0'),
  (171, 16, null, null, 3, null,'0','Reverse Crunch with Bridge','0','0'),
  (172, 16, null, null, 3, null,'0','Side Crunch','0','0'),
  (173, 16, null, null, 3, null,'0','Situps with Twist','0','0'),
  (174, 16, null, null, 6, null,'0','Suitcase Crunch with Med Ball','0','0'),
  (175, 9, 2, .4, 1, null, '0','Suitcase Crunch with Med Ball','0','0'),
  (176, 9, null, null, 3, null, '0','Suitcase Crunch','0','0'),
  (177, 1, 1, .5, 1, null, '0','Sumo Deadlift','0','0'),
  (178, 15, null, null, 3, null, '0','Superman','0','0'),
  (179, 16, null, null, 4, null, '0','TRX Ab Complex','0','1'),
  (180, 10, null, null, 3, null, '0','TRX Curl','0','0'),
  (183, 10, null, null, 3, null, '0','TRX Row','0','0'),
  (181, 6, null, null, 3, null, '0','TRX French Curl','0','0'),
  (182, 6, null, null, 3, null, '0','TRX Pushup','0','0'),
  (184, 2, null, null, 3, null, '0','TRX Single Leg Lunge','0','0'),
  (185, 2, null, null, 3, null, '0','TRX Single Leg Squat','0','0'),
  (186, 16, 2, .17, 8, null, '0','Upper Ab Crunch','0','0'),
  (187, 16, null, null, 3, null, '0','V Ups','0','0'),
  (188, 16, null, null, 6, null, '0','Single Leg Med Ball Slams','0','0');
/*!40000 ALTER TABLE exercises ENABLE KEYS */;


/*!40000 ALTER TABLE tips DISABLE KEYS */;
INSERT INTO tips (exercise_type, tip, exercise_id)
VALUES
  (2,'Try to have your arms and legs meet in the middle.',189),
  (2,'Don''t let your hands or feet touch the ground.',189),
  (2,'Keep your legs as straight as possible.',190),
  (2,'Maintain good posture by squeezing your shoulder blades, and keeping your shoulders rolled back.',191),
  (2,'This isn''t strictly a horizontal pull exercise, but it fits best in this category.',193),
  (2,'Keep your knees slightly bent, and go for speed.',192),
  (2,'This isn''t strictly a horizontal pull exercise, but it fits best in this category.',193),
  (2,'Keep your knees slightly bent, and go for speed.',193),
  (2,'This isn''t strictly a horizontal pull exercise, but it fits best in this category.',194),
  (2,'Keep your knees slightly bent, and go for speed.',194),
  (2,'This isn''t strictly a horizontal pull exercise, but it fits best in this category.',137),
  (2,'Keep your knees slightly bent, and go for speed.',137),
  (2,'Go for half the recommended time on one side, and then switch arms.',137),
  (2,'This isn''t strictly a horizontal pull exercise, but it fits best in this category.',138),
  (2,'Keep your knees slightly bent, and go for speed.',138),
  (2,'This isn''t strictly a horizontal pull exercise, but it fits best in this category.',139),
  (2,'Keep your knees slightly bent, and go for speed.',139),
  (2,'Keep the movement equal with both arms. Don''t allow one arm to do more work than the other.',139),
  (2,'This isn''t strictly a horizontal pull exercise, but it fits best in this category.',140),
  (2,'Keep your knees slightly bent, and go for speed.',140),
  (2,'Go for half the recommended time on one side, and then switch arms.',140),
  (2,'This is a full body exercise, so be sure to get your legs involved.',141),
  (2,'Extend up on your toes while bringing the ropes over your head, then bring the ropes down forcefully while sitting back into a squat.',141),
  (2,'Use the force of your hips to help swing the kettlebell up. This should be more of a leg exercise than an arm exercise.',142),
  (2,'Use the force of your hips to help swing the kettlebell up. This should be more of a leg exercise than an arm exercise.',160),
  (2,'Move down slowly and up forcefully.',143),
  (2,'Hold the medicine ball away from your body to make this exercise more challenging.',143),
  (2,'Primarily push through the arm that''s on top of the bosu.',144),
  (2,'Keep the bosu and steady as possible. Squeeze your core and glutes for stability.',145),
  (2,'Keep the bosu and steady as possible. Squeeze your core and glutes for stability.',146),
  (2,'Row quickly and land softly.',147),
  (2,'Perform the total recommended reps on one side, then switch and do the same on the other side. That''s one set.',148),
  (2,'Perform for the recommended time on one leg, then switch legs and perform for the recommended time. That''s one set.',149),
  (2,'To fulfill your recommended weight load, you can use a dumbbell, weight plate, or kettlebell.',150),
  (2,'The arm movements illustrated in the video are optional.',151),
  (2,'Make sure you keep your body from rotating.',151),
  (2,'As you work yourself around the bar, you should be working your biceps. Do not work yourself around while in a dead hang.',152),
  (2,'Don''t allow your knee to come forward over your toe.',153),
  (2,'Keep your chest up and sit back into a squat.',153),
  (2,'For each set, do the total number of recommended reps on each leg.',153),
  (2,'Stand with your feet about hip width apart.',154),
  (2,'Step one leg backwards, and across the opposite leg, landing on the ball of your foot.',154),
  (2,'Lower into a lunge position, and then immediately drive your self back to the starting position.',154),
  (2,'One repetition = performing the lunge with each leg once.',154),
  (2,'Work to get your elbow over and outside of your knee.',155),
  (2,'Do as many as you can on one side, then switch to the other side. That''s one set.',155),
  (2,'Use an overhand grip.',156),
  (2,'Don''t allow your upper body to rotate as you work through the complex.',157),
  (2,'You can work through all these variations at your own pace.',157),
  (2,'Hold the kettlebell just below your knees.',158),
  (2,'Keep your back straight.',158),
  (2,'Keep your back straight.',159),
  (2,'Pushing through your heels, explode into a standing position, rotating the kettlebell at the top.',158),
  (2,'Pushing through your heels, explode into a standing position, rotating the kettlebell at the top.',159),
  (2,'Spring off of the ground as quickly as possible.',161),
  (2,'Try to fire the medicine ball in a straight line at the wall.',161),
  (2,'Perform the recommended number of reps on one side, and then switch sides. That''s one set.',162),
  (2,'Wedge the bottom of the bar up against a wall, or in a crack against the floor. It''s imperative that the bottom of the bar doesn''t slide out while you''re performing this exercise.',162),
  (2,'The recommended weight for this exercise is just for the weight plate. It does not include the weight of the bar.',162),
  (2,'Perform this exercise at a moderate pace. It is not meant to be performed for speed.',163),
  (2,'Tighten your stomach and focus on keeping your lower back pressed to the floor.',163),
  (2,'The power you use to fire the medicine ball into the wall should come from your hips.',164),
  (2,'Bridge up on every other repetition.',165),
  (2,'Bridge up on every other repetition.',171),
  (2,'Bend your knees slightly for balance.',166),
  (2,'Perform the plank for half the recommended time with one arm, and then switch for the remaining time.',167),
  (2,'Keep your upper back tensed and your shoulders rolled back.',168),
  (2,'Transferring the weights from one side to the other, and then back, is one rep.',168),
  (2,'The goal is to have the glute and hip fire simultaneously.',168),
  (2,'Focus on squeezing your abs and glutes for stability.',169),
  (2,'Push through the hand that''s on the medicine ball.',170),
  (2,'Focus on maintaining a straight back.',170),
  (2,'Bring your feet up as high as your arms and head.',172),
  (2,'Hold the crunch for a count before releasing back down.',172),
  (2,'Your back will curve, but attempt to keep it as straight as possible, using your abs to raise and lower your upper body.',173),
  (2,'Move your arms and legs simultaneously.',174),
  (2,'Move your arms and legs simultaneously.',175),
  (2,'Move your arms and legs simultaneously.',176),
  (2,'Your arms should go up, not behind you.',174),
  (2,'Your arms should go up, not behind you.',175),
  (2,'Keep your back straight, and don''t allow your knees to come forward over your toes.',177),
  (2,'Flex your glutes for stability.',178),
  (2,'Flex your glutes for stability.',179),
  (2,'Don''t allow your hands to raise above eye level.',178),
  (2,'Use your glutes and abs to keep your body in a straight line.',180),
  (2,'Use your glutes and abs to keep your body in a straight line.',181),
  (2,'Use your glutes and abs to keep your body in a straight line.',182),
  (2,'Use your glutes and abs to keep your body in a straight line.',183),
  (2,'Perform as many as you can on one leg, then switch legs. That''s one set.',184),
  (2,'Perform as many as you can on one leg, then switch legs. That''s one set.',185),
  (2,'Don''t allow your knee to come forward over your toe.',184),
  (2,'Don''t allow your knee to come forward over your toe.',185),
  (2,'Your arms should be used primarily to help you keep balance, but the majority of the work should be done with your legs.',185),
  (2,'Hold for a count at the top of the crunch, and slowly release back down.',186),
  (2,'Be sure that your arms and legs meet in the middle.',187),
  (2,'Use your core to fire the ball forward, not solely your arms.',188),
  (2,'Perform a set on one leg, and then switch legs for the next set.',188);
/*!40000 ALTER TABLE tips ENABLE KEYS */;