update performed_exercises set exercise_id = 86 where exercise_id = 117;
update group_performed_exercises set exercise_id = 86 where exercise_id = 117;
delete from exercises where id = 117;
delete from user_maxes where exercise_id = 117;
update performed_exercises set exercise_id = 76 where exercise_id = 75;
update group_performed_exercises set exercise_id = 76 where exercise_id = 75;
delete from exercises where id = 75;
delete from user_maxes where exercise_id = 75;
update performed_exercises set exercise_id = 163 where exercise_id = 110;
update group_performed_exercises set exercise_id = 163 where exercise_id = 110;
delete from exercises where id = 110;
delete from user_maxes where exercise_id = 110;
update performed_exercises set exercise_id = 111 where exercise_id = 112;
update group_performed_exercises set exercise_id = 111 where exercise_id = 112;
delete from exercises where id = 112;
delete from user_maxes where exercise_id = 112;
update performed_exercises set exercise_id = 163 where exercise_id = 113;
update group_performed_exercises set exercise_id = 163 where exercise_id = 113;
delete from exercises where id = 113;
delete from user_maxes where exercise_id = 113;

update performed_plyometrics set plyometric_id = 33 where plyometric_id = 2;
update group_performed_plyos set plyometric_id = 33 where plyometric_id = 2;
delete from plyometrics where id = 2;
update performed_plyometrics set plyometric_id = 9 where plyometric_id = 4;
update group_performed_plyos set plyometric_id = 9 where plyometric_id = 4;
delete from plyometrics where id = 4;
update performed_plyometrics set plyometric_id = 35 where plyometric_id = 5;
update group_performed_plyos set plyometric_id = 35 where plyometric_id = 5;
delete from plyometrics where id = 5;
update performed_plyometrics set plyometric_id = 36 where plyometric_id = 7;
update group_performed_plyos set plyometric_id = 36 where plyometric_id = 7;
delete from plyometrics where id = 7;
update performed_plyometrics set plyometric_id = 30 where plyometric_id = 13;
update group_performed_plyos set plyometric_id = 30 where plyometric_id = 13;
delete from plyometrics where id = 13;

update performed_warm_ups set warmup_id = 5 where warmup_id = 7;
update group_performed_warmups set warmup_id = 5 where warmup_id = 7;
delete from warmups where id = 7;
update performed_warm_ups set warmup_id = 3 where warmup_id = 9;
update group_performed_warmups set warmup_id = 3 where warmup_id = 9;
delete from warmups where id = 9;