INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time)
VALUES (1, 1, '176552753', 1, 0.65, 1, 2, false, 'Clean Pull', false, null, null, 1, false);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time)
VALUES (2, 1, '176556418', 1, 0.25, 1, 2, false, 'Squat Jump', false, null, null, 1, false);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time)
VALUES (3, 1, '176556603', 1, 0.68, 1, 2, false, 'Snatch Pull', false, null, null, 1, false);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time)
VALUES (4, 1, '176553001', 2, 0.23, 2, 2, false, 'One Arm Dumbbell Snatch', false, null, null, 1, false);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time)
VALUES (5, 1, '176552965', 1, 0.71, 1, 2, false, 'Hang Jump Shrug', false, null, null, 1, false);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time)
VALUES (6, 1, '176555134', 1, 0.58, 1, 2, false, 'Clean High Pull', false, null, null, 1, false);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time)
VALUES (7, 1, '176556601', 1, 0.58, 1, 2, false, 'Snatch High Pull', false, null, null, 1, false);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time)
VALUES (8, 1, '83347321', 1, 0.48, 1, null, false, 'Hang Power Clean', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (9, 1, '83080931', 1, 0.48, 1, null, false, 'Hang Power Snatch', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (10, 1, '83083262', 1, 0.48, 1, null, false, 'Power Clean', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (11, 1, '83395098', 1, 0.48, 1, null, false, 'Power Snatch', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (12, 2, '83079576', 1, 0.48, 1, null, false, 'Forward Lunge', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (13, 2, '83083768', 1, 0.5, 1, null, false, 'Reverse Lunge', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (14, 2, '83084249', 1, 0.48, 1, null, false, 'Side Lunge', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (15, 2, '83079006', 1, 0.52, 1, null, false, 'Drop Lunge', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (16, 2, '83085721', 1, 0.55, 1, null, false, 'Stepup', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (17, 2, '83082122', 1, 0.55, 1, null, false, 'Lateral Stepup', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (18, 2, '83077931', 1, 0.48, 1, null, false, 'Bulgarian Split Squat', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (19, 2, '83077697', 1, 0.49, 1, null, false, 'Bulgarian Split Deadlift', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (20, 2, '83085056', 1, 0.32, 1, null, false, 'Single Leg Squats', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (21, 3, '83357082', 1, 1, 1, null, false, 'Squat', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (22, 3, '83079809', 1, 0.62, 1, null, false, 'Front Squat', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (23, 3, '83082985', 2, 0.25, 1, null, false, 'Overhead Squat', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (24, 3, '83085523', 1, 0.72, 1, null, false, 'Split Squat', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (25, 3, '83084250', 1, 0.49, 1, null, false, 'Side Squat', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (26, 4, '83348003', 1, 0.44, 1, null, false, 'Single Leg Good Morning', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (27, 4, '83357079', 1, 0.36, 1, null, false, 'Single Leg Romanian Deadlift', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (28, 4, '83084856', 1, 0.15, 9, null, false, 'Single Leg Back Extension', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (29, 4, '83085057', null, null, 3, null, false, 'Single Leg Supine Hip Extension', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (30, 4, '83085058', null, null, 3, null, false, 'Single Leg Swiss Ball Pull In', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (31, 5, '83083772', 1, 0.77, 1, null, false, 'Romanian Deadlift', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (32, 5, '83079811', 1, 0.55, 1, null, false, 'Good Morning', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (33, 6, '83082801', 2, 0.4, 2, null, false, 'One Arm Dumbbell Decline Press', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (34, 5, '83076503', 1, 0.19, 9, null, false, 'Back Extension', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (35, 5, '83085724', null, null, 3, null, false, 'Supine Hip Extension', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (36, 5, '83085730', null, null, 3, null, false, 'Swiss Ball Pull In', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (38, 6, '83079009', 2, 0.45, 2, null, false, 'Dumbbell Bench Press', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (39, 6, '83079339', 2, 0.3, 2, null, false, 'Dumbbell Incline Press', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (40, 6, '83079338', 2, 0.4, 2, null, false, 'Dumbbell Decline Press', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (41, 6, '83076193', 2, 0.45, 2, null, false, 'Alternating Dumbbell Bench Press', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (42, 6, '83076197', 2, 0.27, 2, null, false, 'Alternating Dumbbell Incline Press', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (43, 6, '83076196', 2, 0.3, 2, null, false, 'Alternating Dumbbell Decline Press', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (44, 6, '83084625', 2, 0.45, 2, null, false, 'One Arm Dumbbell Bench Press', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (45, 6, '83084627', 2, 0.3, 2, null, false, 'One Arm Dumbbell Incline Press', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (46, 6, '83082800', 2, 0.52, 7, null, false, 'One Arm Cable Chest Press', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (47, 7, '83077356', 2, 1, 1, null, false, 'Bench Press', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (48, 7, '83081676', 2, 0.85, 1, null, false, 'Incline Press', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (49, 7, '83078730', 2, 0.89, 1, null, false, 'Decline Press', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (50, 7, '83078154', 2, 0.87, 1, null, false, 'Close Grip Bench Press', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (51, 7, '83078420', 2, 0.67, 1, null, false, 'Close Grip Incline Press', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (52, 7, '83078419', 2, 0.77, 1, null, false, 'Close Grip Decline Press', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (53, 7, '83083534', null, null, 3, null, true, 'Pushup', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (54, 13, '83076497', 3, 1.5, 7, null, true, 'Assisted Pullup', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (55, 7, '83078733', null, null, 3, null, true, 'Decline Pushup', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (56, 7, '83081188', null, null, 3, null, true, 'Incline Pushup', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (57, 7, '83078736', null, null, 3, null, true, 'Dip', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (58, 7, '83076350', 2, 1.25, 7, null, true, 'Assisted Dip', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (59, 7, '83078734', 2, 1.5, 8, null, true, 'Dip With Dip Belt', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (60, 8, '83079007', 2, 0.25, 2, null, false, 'Dumbbell Alternating Press', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (61, 8, '83079569', 2, 0.25, 2, null, false, 'Dumbbell Press', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (62, 8, '83079344', 2, 0.25, 2, null, false, 'Dumbbell One Arm Press', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (63, 8, '83084623', null, null, 3, null, true, 'Side To Side Jackknife Pushup', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (64, 9, '83084242', 2, 0.6, 1, null, false, 'Shoulder Press', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (65, 9, '83347999', 2, 0.35, 1, null, false, 'Push Jerk', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (66, 9, '83357081', 2, 0.35, 1, null, false, 'Split Jerk', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (67, 9, '83395245', 2, 0.5, 1, null, false, 'Push Press', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (68, 9, '83081189', null, null, 3, null, true, 'Jackknife Pushup', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (69, 10, '83077360', 3, 0.54, 2, null, false, 'Bent Over Dumbbell Alternating Row', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (70, 10, '83077359', 3, 0.5, 2, null, false, 'Bent Over 2 Point Dumbbell Row', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (71, 10, '83082984', 3, 0.98, 7, null, false, 'One Arm Standing Cable Row', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (72, 10, '83080934', null, null, 3, null, false, 'Horizontal Side To Side Pullup', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (73, 10, '83082804', null, null, 3, null, false, 'One Arm Horizontal Pullup', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (74, 11, '83077362', 3, 1, 1, null, false, 'Bent Over Row', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (75, 11, '83085966', 3, 0.9, 8, null, false, 'T Bar Row', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (76, 11, '83080932', null, null, 3, null, false, 'Horizontal Pullup', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (77, 11, '83079574', null, null, 3, null, false, 'Elevated Horizontal Pullup', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (78, 11, '83085528', 3, 1.27, 7, null, false, 'Standing Cable Row To Abdomen', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (79, 11, '83085720', 3, 1.04, 7, null, false, 'Standing Cable Row To Neck', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (80, 12, '83084630', 3, 0.72, 7, null, false, 'Single Arm Pulldown', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (81, 12, '83084624', null, null, 3, null, true, 'Side To Side Pullup', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (82, 13, '83081883', 3, 1.3, 7, null, false, 'Lat Pulldown', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (83, 13, '83078149', null, null, 3, null, true, 'Chinup', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (84, 13, '83083529', null, null, 3, null, true, 'Pullup', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (85, 13, '83085971', null, null, 3, null, true, 'Wide Grip Pullup', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (86, 14, '83084240', 3, 0.34, 9, null, false, 'Seated Russian Twist', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (87, 14, '83078426', 2, 0.17, 9, null, false, 'Corkscrew', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (88, 14, '83085965', 2, 0.1, 9, null, false, 'Swiss Ball Weight Roll', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (89, 14, '83086229', null, null, 3, null, false, 'Windshield Wiper', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (90, 14, '83077937', 2, 0.42, 7, null, false, 'Cable Rotation', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (91, 14, '83077939', 2, 0.53, 7, null, false, 'Cable Wood Chop', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (92, 14, '83083764', 2, 0.64, 7, null, false, 'Reverse Cable Wood Chop', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (93, 14, '83077933', 2, 0.91, 7, null, false, 'Cable Rotating Crunch', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (94, 14, '83077936', 2, 0.61, 7, null, false, 'Cable Rotating Extension', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (95, 14, '83082366', 2, 1, 6, null, false, 'Medicine Ball Standing Wall Throw', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (96, 14, '83082363', 2, 1, 6, null, false, 'Medicine Ball 1-2-3 Throw', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (97, 14, '83082365', 2, 1, 6, null, false, 'Med Ball Over The Shoulder Throw', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (98, 15, 'https://s3.amazonaws.com/qfimg/4+point+plank.jpg', null, null, 4, null, false, '4 Point Plank', true, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (99, 15, 'https://s3.amazonaws.com/qfimg/3+point+plank.jpg', null, null, 4, null, false, '3 Point Plank', true, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (100, 15, 'https://s3.amazonaws.com/qfimg/2+point+plank.jpg', null, null, 4, null, false, '2 Point Plank', true, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (101, 15, 'https://s3.amazonaws.com/qfimg/side+bridge.jpg', null, null, 4, null, false, 'Side Bridge', true, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (102, 15, 'https://s3.amazonaws.com/qfimg/4+point+supine+bridge.jpg', null, null, 4, null, false, '4 Point Supine Bridge', true, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (103, 15, '/img/exImages/3 point supine bridge.jpg', null, null, 4, null, false, '3 Point Supine Bridge', true, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (104, 15, '83079573', null, null, 4, null, false, 'Dynamic Plank', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (105, 15, '83082988', null, null, 4, null, false, 'Plank w/ Elbow To Knee', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (106, 15, '83084247', null, null, 4, null, false, 'Side Bridge and Reach', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (107, 15, '83078424', 3, 0.48, 2, null, false, 'Core Row', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (108, 15, '83076504', null, null, 4, null, false, 'Barbell Rollout', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (109, 16, '83079005', null, null, 3, null, false, 'Double Crunch', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (110, 16, '83082124', null, null, 3, null, false, 'Leg Raises', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (111, 16, '83083766', null, null, 3, null, false, 'Reverse Crunch', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (112, 16, '83084009', null, null, 3, null, false, 'Scissor Kick With Lift', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (113, 16, '83084010', null, null, 3, null, false, 'Scissor Kick', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (114, 16, '83085727', null, null, 3, null, false, 'Swiss Ball Crunch', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (115, 16, '83078728', null, null, 3, null, false, 'Crunch', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (116, 16, '83077366', null, null, 3, null, false, 'Bicycle', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (117, 16, '83082989', 2, 0.24, 9, null, false, 'Plate Twists', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (118, 7, '83083265', null, null, 3, null, true, 'Power Pushup', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (119, 7, '83076499', null, null, 3, null, true, 'Assisted Pushup', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (120, 13, '83082370', 3, 1.22, 7, null, false, 'Neutral Grip Pulldown', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (121, 11, '83084012', 3, 1, 7, null, false, 'Seated Cable Row', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (122, 2, '83078427', 1, 0.5, 1, null, false, 'Cross Lateral Stepup', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (123, 2, '83079572', 1, 0.23, 2, null, false, 'Dumbbell Stepup', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (124, 2, '83079340', 1, 0.23, 2, null, false, 'Dumbbell Lateral Stepup', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (125, 2, '83079011', 1, 0.2, 2, null, false, 'Dumbbell Cross Lateral Stepup', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (126, 1, '83347323', 2, 0.35, 1, null, false, 'Power Clean And Jerk', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (127, 1, '83347991', 2, 0.6, 1, null, false, 'Power Clean And Press', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (128, 1, '83347320', 2, 0.35, 1, null, false, 'Hang Power Clean And Jerk', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (129, 1, '83347319', 2, 0.5, 1, null, false, 'Hang Power Clean And Press', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (130, 9, '83085301', 2, 0.48, 1, null, false, 'Split Push Press', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (131, 13, '83076198', 3, 1.5, 7, null, true, 'Assisted Chinup', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (132, 13, '83076501', 3, 1.3, 7, null, true, 'Assisted Wide Grip Pullup', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (133, 13, '83083271', 3, 1.7, 8, null, true, 'Pullup With Dip Belt', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (134, 13, '83078147', 3, 1.7, 8, null, true, 'Chinup With Dip Belt', false, null, null, 1, null);
INSERT INTO exercises (id, exercise_type_id, video_link, look_up_value, percent_of_luv, category, difficulty, is_body_weight, name, is_image, created_at, updated_at, paid_tier, for_time) VALUES (135, 13, '83085974', 3, 1.5, 8, null, true, 'Wide Grip Pullup With Dip Belt', false, null, null, 1, null);

INSERT INTO exercises (id, exercise_type_id, look_up_value, percent_of_luv, category, difficulty,
                       is_body_weight, name, is_image, for_time)
VALUES (189,16,null,null,3,null,'0','2 to 1 V Up','0','0'),
  (190,15,null,null,4,null,'0','6 Inches','0','1'),
  (191, 11, 3, 1, 7, null,'0','Angled Cable Row','0','0'),
  (192, 11, null, null, 4, null,'0','Battleropes Big Circles','0','1'),
  (193, 11, null, null, 4, null,'0','Battleropes Drummers','0','1'),
  (194, 11, null, null, 4, null,'0','Battleropes Front Raises','0','1'),
  (137, 11, null, null, 4, null,'0','Battleropes Lateral Raises','0','1'),
  (138, 11, null, null, 4, null,'0','Battleropes Outward Circles','0','1'),
  (139, 11, null, null, 4, null,'0','Battleropes Side to Side','0','1'),
  (140, 11, null, null, 4, null,'0','Battleropes Single Arm Circles','0','1'),
  (141, 1, null, null, 4, null,'0','Battleropes Slams','0','1'),
  (142, 1, 2, .4, 2, null,'0','Bosu Kettlebell Swing Through','0','0'),
  (143, 9, null, null, 6, null,'0','Bosu Low to High Chop with Med Ball','0','0'),
  (144, 6, null, null, 3, null,'0','Bosu Over and Back Pushup','0','0'),
  (145, 15, null, null, 4, null,'0','Bosu Plank 1','0','1'),
  (146, 15, null, null, 4, null,'0','Bosu Plank 2','0','1'),
  (147, 6, null, null, 3, null,'0','Bosu Pushup','0','0'),
  (148, 8, 2, .24, 2, null,'0','Bosu Single Leg Shoulder Press','0','0'),
  (149, 2, null, null, 4, null,'0','Bosu Single Leg Squat','0','1'),
  (150, 2, 2, .17, 9, null,'0','Bosu Single Leg Squat','0','0'),
  (151, 14, 3, .6, 7, null,'0','Cable Core Anti Rotation','0','1'),
  (152, 14, null, null, 3, null,'0','Cliffhangers','0','0'),
  (153, 2, 1, .52, 1, null,'0','Dumbbell Bulgarian Split Squat','0','0'),
  (154, 2, 1, .52, 1, null,'0','Dumbbell Drop Lunge','0','0'),
  (155, 16, null, null, 3, null,'0','Elbow to Knee','0','0'),
  (156, 10, null, null, 3, null,'0','Elevated Horizontal Side to Side Pullup','0','0'),
  (157, 15, null, null, 4, null,'0','Front Plank Complex','0','1'),
  (158, 1, 2, .23, 2, null,'0','Hang Kettlebell Snatch','0','0'),
  (159, 1, 2, .23, 2, null,'0','Kettlebell Snatch','0','0'),
  (160, 1, 2, .45, 2, null,'0','Kettlebell Swing Through','0','0'),
  (161, 7, null, null, 6, null,'0','Kneeling Med Ball Wall Blasts','0','0'),
  (162, 1, null, null, 8, null,'0','Landmine with Extension','0','0'),
  (163, 16, null, null, 8, null,'0','Little Bigs','0','0'),
  (164, 14, null, null, 6, null,'0','Med Ball Front Rotation','0','0'),
  (165, 16, null, null, 6, null,'0','Med Ball Reverse Crunch with Bridge','0','0'),
  (166, 7, null, null, 6, null,'0','Med Ball Wall Blasts','0','0'),
  (167, 15, null, null, 4, null,'0','One Arm Bosu Plank','0','1'),
  (168, 2, 1, .52, 1, null,'0','Paperboy','0','0'),
  (169, 15, null, null, 4, null,'0','Swiss Ball Plank Complex','0','1'),
  (170, 6, null, null, 3, null,'0','Plyo Pushup with Med Ball','0','0'),
  (171, 16, null, null, 3, null,'0','Reverse Crunch with Bridge','0','0'),
  (172, 16, null, null, 3, null,'0','Side Crunch','0','0'),
  (173, 16, null, null, 3, null,'0','Situps with Twist','0','0'),
  (174, 16, null, null, 6, null,'0','Suitcase Crunch with Med Ball','0','0'),
  (175, 9, 2, .4, 1, null, '0','Suitcase Crunch with Med Ball','0','0'),
  (176, 9, null, null, 3, null, '0','Suitcase Crunch','0','0'),
  (177, 1, 1, .5, 1, null, '0','Sumo Deadlift','0','0'),
  (178, 15, null, null, 3, null, '0','Superman','0','0'),
  (179, 16, null, null, 4, null, '0','TRX Ab Complex','0','1'),
  (180, 10, null, null, 3, null, '0','TRX Curl','0','0'),
  (183, 10, null, null, 3, null, '0','TRX Row','0','0'),
  (181, 6, null, null, 3, null, '0','TRX French Curl','0','0'),
  (182, 6, null, null, 3, null, '0','TRX Pushup','0','0'),
  (184, 2, null, null, 3, null, '0','TRX Single Leg Lunge','0','0'),
  (185, 2, null, null, 3, null, '0','TRX Single Leg Squat','0','0'),
  (186, 16, 2, .17, 8, null, '0','Upper Ab Crunch','0','0'),
  (187, 16, null, null, 3, null, '0','V Ups','0','0'),
  (188, 16, null, null, 6, null, '0','Single Leg Med Ball Slams','0','0');